-- Migration: Seed 123 default teas from teas.ts
-- All teas get source_type='default', source='Teapp', is_public=TRUE, owner_id=NULL

-- First, add new columns to teas table
ALTER TABLE teas ADD COLUMN IF NOT EXISTS source_type TEXT DEFAULT 'default' CHECK (source_type IN ('default', 'user', 'teahouse'));
ALTER TABLE teas ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'Teapp';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS phonetic_name TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS original_name TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS brewing_num_brews INT DEFAULT 1;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS brewing_instructions TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS health_benefits TEXT[] DEFAULT '{}';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS color_hex TEXT DEFAULT '#999';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS oxidation_level INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS roast_level INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS flavor_x INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS flavor_y INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS wikidata_qid TEXT;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS caffeine_level TEXT DEFAULT 'medium';

UPDATE teas SET source_type = 'default', source = 'Teapp', is_public = TRUE WHERE source_type IS NULL OR source_type = 'default';

-- Insert 123 default teas (ON CONFLICT on slug DO NOTHING if already exists)
-- Using a single transaction
INSERT INTO teas (name, slug, phonetic_name, original_name, description, origin, tea_type, category, caffeine_level, brewing_temp_c, brewing_time_min, brewing_num_brews, brewing_instructions, characteristics, health_benefits, color_hex, oxidation_level, roast_level, flavor_x, flavor_y, source_type, source, owner_id, is_public, wikidata_qid) VALUES
  ('24 Flavors', '24-flavors', '', '二十四味', 'Cantonese herbal tea', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Aged White Tea', 'aged-white-tea', '', '老白茶', 'White tea that has been naturally aged for several years (typically 3–20+). As white tea ages, its character transforms profoundly: the fresh floral and delicately sweet notes of youth deepen into rich honey, dried fruit, and woody complexity. Revered in Chinese tea culture for the saying "one year tea, three years medicine, seven years treasure" — aged white tea is believed to gain both flavour and therapeutic value with time.', 'Fujian, China', 'white', 'true_tea', 'low', 95, 5, 5, 'Use 5g per 150ml of water at 90–95°C — hotter than fresh white tea. Rinse once (10 seconds, discard) to awaken the aged leaves. First infusion: 20–30 seconds gongfu style, adding 10 seconds per subsequent steep. Can yield 8+ infusions. For older teas (7+ years), try simmering 5g in 500ml water for 5–10 minutes for a rich, warming cup.', ARRAY['Honey','Woody','Dried Fruit','Sweet']::text[], ARRAY['Rich in Antioxidants','Reduces Inflammation','Boosts Immune System','Aids Digestion']::text[], '#C8C4B0', 10, 5, 30, 15, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Asamushi', 'asamushi', '', '浅蒸し', 'type of sencha green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Assam', 'assam', '', '', 'Grown in the lush Brahmaputra river valley of northeastern India — the world''s largest tea-growing region. Assam is a robust, full-bodied black tea with a bold malty character, deep amber liquor, and the backbone of most classic British breakfast blends.', 'Assam, India', 'black', 'true_tea', 'high', 95, 4, 2, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–5 minutes. Assam stands up beautifully to milk and sugar. The foundation of English Breakfast and Irish Breakfast blends. CTC (crush-tear-curl) Assam brews faster and stronger than whole-leaf.', ARRAY['Bold','Malty','Earthy']::text[], ARRAY['Rich in Antioxidants','Improves Energy Levels','Boosts Heart Health']::text[], '#8B4513', 90, 70, 85, 65, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Bai Jiguan tea', 'bai-jiguan-tea', '', '白雞冠', 'Well-known oolong tea of Wuyi', 'China', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Baimao Hou', 'baimao-hou', '', '白毛猴', 'green tea from the Taimu Mountains in Fujian Province, China', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ban Tian Yao tea', 'ban-tian-yao-tea', '', '半天腰', 'A rarely seen Mount Wuyi Oolong with a light smokey taste', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Bancha', 'bancha', '', '番茶', 'Japanese green tea', 'Japan', 'green', 'true_tea', 'low', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Baozhong', 'baozhong', '', '包種茶', 'famous Taiwan spring tea between green and oolong', 'Taiwan', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Biluochun', 'biluochun', '', '碧螺春', 'famous Chinese green tea from Dongting Mountains, near Suzhou', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Bu Zhi Chun tea', 'bu-zhi-chun-tea', '', '不知春', 'a rarely seen Mount Wuyi Oolong with a light taste', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ceylon', 'ceylon', '', '', 'Sri Lanka''s flagship black tea, named for the island''s colonial-era name. Grown across multiple high-altitude regions, Ceylon teas are known for their bright amber liquor, brisk character, and distinctive notes of citrus, cocoa, and spice with 50–90mg of caffeine per cup.', 'Sri Lanka', 'black', 'true_tea', 'high', 95, 4, 2, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–4 minutes. Excellent with or without milk. Uva region teas (high altitude) have the most distinctive spicy character; Nuwara Eliya produces a lighter, more delicate cup.', ARRAY['Bold','Citrusy','Malty']::text[], ARRAY['Rich in Antioxidants','Improves Focus','Boosts Heart Health']::text[], '#8B4513', 90, 70, 73, 55, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Chamomile Mint', 'chamomile-mint', '', '', 'A soothing herbal infusion blending calming chamomile with refreshing peppermint. The gentle sweetness of chamomile flowers balances the cooling menthol of peppermint for a tisane that is both relaxing and invigorating.', 'Egypt / United States', 'tisane', 'tisane', 'none', 100, 5, 2, 'Use 1.5 tsp (3–4g) per 8oz (240ml) of boiling water. Steep covered for 5 minutes to trap the essential oils. The blend is forgiving — longer steeping intensifies without becoming bitter. Add honey to enhance sweetness.', ARRAY['Floral','Minty']::text[], ARRAY['Promotes Sleep & Relaxation','Aids Digestion']::text[], '#C0856A', 40, 30, 12, 10, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Chik-Cha', 'arrowroot-tea', '', '칡차', 'beverage made by infusing arrowroot roots', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Chrysanthemum Tea', 'chrysanthemum-tea', '', '菊花茶', 'beverage made by infusing dried flowers of chrysanthemum', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Chūmushi', 'chūmushi', '', '中蒸し', 'type of sencha green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Corn Tea', 'corn-tea', '', '옥수수차', 'beverage made by infusing roasted corn kernels', 'South Korea', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Daechu-Cha', 'daechu-cha', '', '대추차', 'traditional Korean beverage made by infusing dried jujube berries', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dafang tea', 'dafang-tea', '', '頂谷大方', 'Flat green tea from Anhui province (China), similar to Longjing', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Darjeeling', 'darjeeling', '', '', 'Often called the ''Champagne of Teas'', Darjeeling is grown in the misty Himalayan foothills of West Bengal at elevations up to 2,000m. Its famous muscatel character — a musky, grape-like sweetness — is unique in the tea world and protected by geographical indication.', 'Darjeeling, West Bengal, India', 'black', 'true_tea', 'high', 90, 3, 2, 'First flush: use water at 85–90°C and steep 2–3 minutes. Second flush: 90–95°C for 3–4 minutes. Best enjoyed without milk for first flush to appreciate the muscatel notes. Second flush pairs well with a splash of milk.', ARRAY['Floral','Fruity','Malty']::text[], ARRAY['Rich in Antioxidants','Boosts Heart Health','Improves Focus']::text[], '#8B4513', 90, 70, 62, 40, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dian Hong Jin Luo', 'dian-hong-jin-luo', '', '滇红金螺', 'Type of Chinese black tea', '', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dianhong', 'dianhong', '', '滇紅茶', 'type of Chinese black tea grown in Yunnan province', '', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dohwa-Cha', 'peach-blossom-tea', '', '도화차', 'traditional Korean beverage made by infusing the dried peach flowers', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Doncha', 'doncha', '', '돈차', 'Korean coin-shaped post-fermented tea', 'Korea', 'dark', 'true_tea', 'high', 95, 4, 8, '', '{}'::text[], '{}'::text[], '#6B4226', 40, 30, 78, 55, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dongfang meiren tea', 'dongfang-meiren-tea', '', '東方美人', 'oolong tea', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dragonwell (Long Jing)', 'dragonwell-long-jing', '', '龙井', 'China''s most celebrated green tea, named for a well in the hills of Hangzhou. Pan-fired in a hot wok to create its signature flat, sword-shaped leaves, Dragonwell has a clean chestnut sweetness, delicate vegetal notes, and a lingering finish prized by emperors for centuries.', 'Hangzhou, Zhejiang, China', 'green', 'true_tea', 'medium', 80, 2, 3, 'Use 3g per 200ml of water at 75–80°C. Steep for 1–2 minutes. The second and third infusions are often considered the most flavourful. Use a glass cup to watch the leaves unfurl — part of the traditional Dragonwell experience.', ARRAY['Grassy','Nutty','Sweet']::text[], ARRAY['Rich in Antioxidants','Improves Focus','Boosts Heart Health']::text[], '#7BA05B', 0, 10, 13, 7, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Dried Lime Tea', 'dried-lime-tea', '', 'شاي الليمون المجفف', 'A beverage that widely consumed in Iraq , Kuwait , Oman and United Arab Emirates.', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Duyun Maojian', 'duyun-maojian', '', '都匀毛尖', 'Chinese Green Tea Type', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Earl Grey', 'earl-grey', '', '', 'The world''s most recognisable flavoured tea — a classic black tea blend naturally scented with bergamot oil, named after the British Prime Minister Charles Grey. Its floral citrus fragrance is immediately distinctive.', 'United Kingdom', 'blend', 'blend', 'high', 95, 4, 1, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–5 minutes depending on strength preference. Excellent with a splash of milk or a slice of lemon. Avoid boiling water to preserve the bergamot''s delicate aroma.', ARRAY['Citrusy','Bold']::text[], ARRAY['Rich in Antioxidants','Boosts Heart Health']::text[], '#B07D56', 40, 30, 43, 40, 'default', 'Teapp', NULL, TRUE, NULL),
  ('East Friesland Tea Blend', 'east-friesland-tea-blend', '', 'Ostfriesentee', 'A strong, traditional black tea blend from Ostfriesland, Germany. Primarily Assam tea with Ceylon, African, Java, Sumatra, and Darjeeling varieties. Designed to be enjoyed with cream (Sahne) and rock sugar (Kluntje).', 'Ostfriesland, Germany', 'blend', 'blend', 'high', 95, 4, 1, 'Place rock sugar (Kluntje) in the cup. Pour hot tea over the sugar, then add a spoonful of cream to the edge of the cup to form a Wulkje (small cloud). Do not stir — enjoy the layers: cream first, then the strong tea, then the sweetness.', ARRAY['Strong','Malty','Aromatic','Slightly bitter']::text[], '{}'::text[], '#B07D56', 80, 60, 60, 50, 'default', 'Teapp', NULL, TRUE, NULL),
  ('English Breakfast', 'english-breakfast', '', '', 'The quintessential British morning tea — a robust, full-bodied blend of Assam, Ceylon, and Darjeeling black teas, designed to be paired with milk, hold its own against a hearty breakfast, and provide a strong caffeine start to the day.', 'United Kingdom', 'blend', 'blend', 'high', 95, 4, 1, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–4 minutes. Traditionally served with whole milk added to the cup first, then tea poured over. Sugar is optional. The ratio of teas in the blend varies by producer.', ARRAY['Bold','Malty']::text[], ARRAY['Rich in Antioxidants','Improves Energy Levels','Improves Focus']::text[], '#B07D56', 40, 30, 53, 50, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Fo Shou tea', 'fo-shou-tea', '', '佛手', 'A rarely seen Mount Wuyi Oolong', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Fukamushicha', 'fukamushicha', '', '深蒸し茶', 'kind of green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Fukuju', 'fukuju', '', '福寿', 'type of green tea', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Genmaicha', 'genmaicha', '', '玄米茶', 'Japanese green tea mixed with brown rice', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ginger Root', 'ginger-root', '', '', 'A warming and invigorating tisane brewed from dried slices of Zingiber officinale root. Sharp, fiery, and deeply aromatic, ginger tea has been used in traditional Ayurvedic and Chinese medicine for millennia as a remedy for nausea, poor digestion, and inflammation.', 'India, China & Caribbean', 'tisane', 'tisane', 'none', 100, 5, 2, 'Use 1 tsp (2–3g) of dried ginger root per 8oz (240ml) of boiling water. Steep for 5–10 minutes — longer brewing creates more heat. For fresh ginger, use 3–4 thin slices and simmer for 10 minutes. Add honey and a squeeze of fresh lemon to round out the spice beautifully.', ARRAY['Spicy','Sweet','Earthy']::text[], ARRAY['Aids Digestion','Reduces Inflammation','Boosts Immune System','Improves Energy Levels']::text[], '#C0856A', 40, 30, 35, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ginseng Tea', 'ginseng-tea', '', '人参茶', 'beverage made by infusing ginseng roots', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Goishicha', 'goishicha', '', '碁石茶', 'type of fermented tea', '', 'dark', 'true_tea', 'high', 95, 4, 8, '', '{}'::text[], '{}'::text[], '#6B4226', 40, 30, 78, 55, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Goji Tea', 'goji-tea', '', '枸杞茶', 'traditional Korean and Chinese beverage made by infusing dried goji berries or leaves', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gokmul-Cha', 'seed-tea', '', '곡물차', 'traditional Korean beverages made of seeds of various plants', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Golden Monkey tea', 'golden-monkey-tea', '', '金猴茶', 'a fine black tea from Yunnan province', '', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gunpowder Green', 'gunpowder-green', '', '珠茶', 'Named for its tightly rolled pellets that resemble old musket powder, this bold Chinese green tea from Zhejiang province unfurls dramatically in hot water. Its robust, slightly smoky character makes it one of the longest-lasting green teas in storage.', 'Zhejiang, China', 'green', 'true_tea', 'medium', 80, 3, 3, 'Use 1 tsp (3g) of pellets per 8oz (240ml) of water at 75–80°C. Steep for 2–3 minutes. Overbrewing will intensify bitterness. The traditional base for Moroccan Mint Tea — the pellets hold up well to the addition of sugar and mint.', ARRAY['Smoky','Bold','Earthy']::text[], ARRAY['Rich in Antioxidants','Boosts Immune System']::text[], '#7BA05B', 0, 10, 50, 40, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gyeolmyeongja-Cha', 'gyeolmyeongja-cha', '', '결명자차', 'beverage made by infusing roasted sicklepod grains', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gyepi-Cha', 'gyepi-cha', '', '계피차', 'herbal tea', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gyokuro', 'gyokuro', '', '玉露', 'Japan''s most prized green tea, shaded from sunlight for 20+ days before harvest. The reduced light signals the plant to produce extraordinary levels of L-theanine and chlorophyll, resulting in an intensely umami, sweet, and deeply complex cup known as ''jade dew''.', 'Uji & Yame, Japan', 'green', 'true_tea', 'high', 60, 2, 3, 'Use 5g per 150ml of water at 55–60°C — far cooler than any other tea. Steep for exactly 2 minutes without stirring. The low temperature extracts sweetness and umami while suppressing bitterness. Re-steep 2–3 times, slightly increasing temperature each time.', ARRAY['Umami','Sweet','Grassy']::text[], ARRAY['Rich in Antioxidants','Improves Focus','Boosts Heart Health','Rich in L-Theanine']::text[], '#7BA05B', 0, 10, 5, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Hibiscus', 'hibiscus', '', '', 'A vibrant ruby-red tisane brewed from the dried calyces of Hibiscus sabdariffa, known for its brilliant colour and tart, cranberry-like flavour. Packed with vitamin C and anthocyanins, hibiscus is one of the most visually striking and health-supporting teas in the world.', 'Egypt, Mexico & West Africa', 'tisane', 'tisane', 'none', 100, 5, 2, 'Use 1–2 tsp (2–4g) of dried flowers per 8oz (240ml) of boiling water. Steep for 5–7 minutes for maximum colour and flavour. Excellent served iced — refrigerate after brewing. Add honey or a cinnamon stick to balance the tartness. Known as ''karkadé'' in Egypt and ''agua de jamaica'' in Mexico.', ARRAY['Tart','Fruity','Floral']::text[], ARRAY['Rich in Antioxidants','Boosts Heart Health','Reduces Inflammation','Boosts Immune System']::text[], '#C0856A', 40, 30, 17, 10, 'default', 'Teapp', NULL, TRUE, NULL),
  ('High mountain tea', 'high-mountain-tea', '', '高山茶', 'varieties of oolong tea grown in Taiwan', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Hojicha', 'hojicha', '', '焙じ茶', 'Japanese green tea roasted over charcoal', 'Japan', 'green', 'true_tea', 'low', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Huang Guanyin tea', 'huang-guanyin-tea', '', '黄觀音茶', 'A new cultivar of Mount Wuyi Oolong', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Huang Mei Gui tea', 'huang-mei-gui-tea', '', '黃玫瑰', 'a very new Wuyi Oolong tea', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Huangjin Gui', 'huangjin-gui', '', '黃金桂', 'premium variety of Oolong from Anxi', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Huoshan Huangya tea', 'huoshan-huangya-tea', '', '霍山黄芽', 'yellow tea from Anhui province', 'People''s Republic of China', 'yellow', 'true_tea', 'medium', 80, 2, 3, '', '{}'::text[], '{}'::text[], '#E6C84E', 15, 15, 30, 18, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Irimushi', 'irimushi', '', '炒蒸し', 'type of sencha green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Jasmine Green Tea', 'jasmine-green', '', '茉莉花茶', 'Most famous scented tea in China. Tea base (most commonly green tea, also white, oolong, or black) infused with natural fragrance of jasmine blossoms through a layered absorption process. Subtly sweet and highly fragrant flavor. Initial gentle astringency followed by clean, sweet lingering finish. Fujian-produced jasmine tea has the best reputation in China.', 'Fujian, China (also Jiangsu, Jiangxi, Guangdong, Guangxi, Zhejiang)', 'blend', 'blend', 'medium', NULL, NULL, 1, 'Use 2g per 200ml of water at 80–85°C. Steep for 2–3 minutes. Never use boiling water — it damages the delicate jasmine aroma. Excellent for 2–3 infusions. Jasmine pearls (a rolled variety) are especially beautiful to watch unfurl in a glass cup.', ARRAY['Floral','Sweet','Grassy']::text[], ARRAY['Rich in Antioxidants','Reduces Stress & Anxiety','Promotes Sleep & Relaxation']::text[], '#B07D56', 40, 30, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Jin Fo tea', 'jin-fo-tea', '', '金佛茶', 'medium Wuyi Oolong tea', 'People''s Republic of China', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Jin Jun Mei tea', 'jin-jun-mei-tea', '', '金駿眉', 'type of black tea from the Wuyi Mountains in Fujian Province, China', '', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Junshan Yinzhen', 'junshan-yinzhen', '', '君山銀針;', 'One of China''s Ten Famous Teas and the most celebrated yellow tea in the world. Harvested exclusively from Junshan Island on Dongting Lake in Hunan, each batch uses only the tenderest first-flush buds plucked in a brief spring window. The distinctive sealed yellowing step (闷黄, mén huáng) gently mellows the leaves, yielding a cup that sits between green and white tea — less grassy than the former, with more body than the latter. Expect mellow sweetness, light grain, a whisper of apricot, and a clean lingering finish.', 'Junshan Island, Hunan, China', 'yellow', 'true_tea', 'low', 70, 3, 3, 'Use 3g per 150ml of water at 70–75°C — avoid boiling water, which will mask the subtle sweetness. Steep for 2–3 minutes. Use a glass vessel if possible to watch the silver needle buds dance upright as they unfurl. Can be re-steeped 2–3 times, each infusion revealing slightly different notes.', ARRAY['Sweet','Grassy','Floral','Nutty']::text[], ARRAY['Rich in Antioxidants','Aids Digestion','Reduces Inflammation','Boosts Immune System']::text[], '#E6C84E', 15, 15, 18, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Kamairicha tea', 'kamairicha-tea', '', '釜炒り茶', 'Japanese green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Kangra tea', 'kangra-tea', '', 'कांगड़ा चाय', 'black or green tea from the Kangra district, India', '', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Keemun', 'keemun', '', '祁門紅茶', 'famous Chinese black tea', 'People''s Republic of China', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Kokicha', 'kohki-tea', '', '黄杞茶', 'Japanese herbal drink very high in antioxidant activity', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Konacha', 'konacha', '', '粉茶', 'lower-grade Japanese green tea made up of small leaves and teadust', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Kukicha', 'kukicha', '', '茎茶', 'Japanese tea blend', 'Japan', 'green', 'true_tea', 'low', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 40, 30, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lady Grey', 'lady-grey', '', '', 'trademarked variation on Earl Grey tea', 'England', 'blend', 'true_tea', 'high', 90, 4, 1, '', '{}'::text[], '{}'::text[], '#B07D56', 40, 30, 40, 35, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lapacho', 'lapacho', '', '', 'herbal tea made from a Central and South American tree''s bark', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lapsang Souchong', 'lapsang-souchong', '', '正山小種', 'The world''s first black tea, originating from the Wuyi Mountains in 1646. Its large leaves are withered and dried over smouldering pine wood fires, absorbing an intensely smoky, resinous character that has earned it the nickname ''the whiskey of black teas''.', 'Wuyi Mountains, Fujian, China', 'black', 'true_tea', 'medium', 95, 3, 2, 'Use 2g per 200ml of water at 90–95°C. Steep for 3–4 minutes. Avoid over-steeping to prevent bitterness. Best enjoyed without milk to fully appreciate the smoke. An acquired taste — loved passionately by those who appreciate it.', ARRAY['Smoky','Bold','Woody']::text[], ARRAY['Rich in Antioxidants','Reduces Inflammation','Aids Digestion']::text[], '#8B4513', 90, 70, 92, 65, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lavender', 'lavender', '', '', 'A soothing floral tisane brewed from the dried buds of Lavandula angustifolia. With a delicate, perfumed sweetness and an unmistakable calming aroma, lavender tea has long been treasured in European herbal traditions as an aid to anxiety, insomnia, and restlessness.', 'Provence, France & Mediterranean', 'tisane', 'tisane', 'none', 95, 5, 2, 'Use 1 tsp (1–2g) of dried lavender buds per 8oz (240ml) of water at 90–95°C (avoid boiling — it can make lavender medicinal). Steep for 5 minutes. Pairs beautifully with honey or a slice of lemon. Excellent blended with chamomile for a deeper sleep-promoting effect.', ARRAY['Floral','Sweet','Creamy']::text[], ARRAY['Promotes Sleep & Relaxation','Reduces Stress & Anxiety','Reduces Inflammation']::text[], '#C0856A', 40, 30, 20, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lotus Tea', 'lotus-tea', '', '연잎차', 'beverage made by infusing leaves, flowers, roots of lotus', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Maehwa-Cha', 'plum-blossom-tea', '', '매화차', 'traditional Korean beverage made by infusing the dried plum flowers', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Maesil-Cha', 'maesil-cha', '', '매실차', 'traditional Korean beverage made by diluting the maesil marmalade with water', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Maghrebi Mint Tea', 'maghrebi-mint-tea', '', 'أتاي', 'tea preparation and form of tea consumption in the Maghreb countries', 'Maghreb', 'tisane', 'tisane', 'medium', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Maojian tea', 'maojian-tea', '', '信陽毛尖', 'one of the top Chinese green teas', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Masala Chai', 'masala-chai', '', 'मसाला चाय', 'India''s beloved spiced tea, brewed strong with milk and a warming blend of cardamom, ginger, cinnamon, cloves, and black pepper. Deeply aromatic, invigorating, and comforting — masala chai is as much a ritual as a beverage, sold on every street corner in India.', 'India', 'blend', 'blend', 'high', 100, 5, 1, 'Simmer 1 tsp (2–3g) of strong black tea with 200ml of water and 200ml of whole milk. Crush and add spices: 3–4 cardamom pods, a cinnamon stick, 3 cloves, 2 slices of ginger, and 3–4 black peppercorns. Bring to a boil twice. Strain and sweeten with jaggery or sugar.', ARRAY['Spicy','Sweet','Malty','Creamy']::text[], ARRAY['Aids Digestion','Improves Energy Levels','Boosts Immune System','Reduces Inflammation']::text[], '#B07D56', 40, 30, 53, 27, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Matcha', 'matcha', '', '抹茶', 'A finely stone-ground powder made from shade-grown tencha leaves. Unlike all other teas, matcha is whisked into water rather than steeped — meaning you consume the entire leaf and all its nutrients. One of the most antioxidant-rich foods on earth.', 'Uji, Japan', 'green', 'true_tea', 'high', 80, 1, 3, 'Sift 1–2g of ceremonial grade matcha into a warmed bowl. Add 70–80ml of water at 75–80°C (never boiling). Whisk vigorously in a ''W'' or ''M'' motion until frothy. For usucha (thin tea) use 1g; for koicha (thick tea) use 3–4g and whisk slowly.', ARRAY['Umami','Grassy','Vegetal','Creamy']::text[], ARRAY['Rich in Antioxidants','Improves Focus','Supports Weight Management','Reduces Stress & Anxiety']::text[], '#7BA05B', 0, 10, 5, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Mecha tea', 'mecha-tea', '', '芽茶', 'Popular after-dinner Japanese green tea', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Meng Ding Huangya', 'meng-ding-huangya', '', '蒙顶黄芽', 'yellow tea from Mt. Meng', '', 'yellow', 'true_tea', 'medium', 80, 2, 3, '', '{}'::text[], '{}'::text[], '#E6C84E', 15, 15, 30, 18, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Mengding Ganlu tea', 'mengding-ganlu-tea', '', '蒙頂甘露', 'Chinese green tea with sweet aftertaste', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Mogwa-Cha', 'mogwa-cha', '', '모과차', 'traditional Korean beverage made by diluting the mogwa marmalade with water', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ogwa-Cha', 'ogwa-cha', '', '오과차', 'five-fruit tea', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Omija-Cha', 'omija-cha', '', '오미자차', 'traditional Korean beverage made by infusing dried magnolia berries', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Peppermint', 'peppermint', '', '', 'A crisp, cooling tisane made from the dried leaves of Mentha piperita — a natural hybrid of spearmint and watermint. One of the world''s most popular herbal teas, prized for its intensely clean menthol character, digestive benefits, and invigorating clarity.', 'Europe & North America', 'tisane', 'tisane', 'none', 100, 5, 2, 'Use 1–2 tsp (2–4g) of dried peppermint per 8oz (240ml) of boiling water. Steep covered for 5–7 minutes to trap the volatile menthol oils. Fresh peppermint leaves can be substituted — use 2–3 times the quantity. Peppermint does not turn bitter with extended steeping.', ARRAY['Minty','Sweet','Grassy','Refreshing']::text[], ARRAY['Aids Digestion','Reduces Stress & Anxiety','Boosts Immune System']::text[], '#C0856A', 40, 30, 5, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Persimmon Leaf Tea', 'persimmon-leaf-tea', '', '감잎차', 'traditional Korean beverage made by infusing dried leaves of persimmon', 'Korea', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ppuri-Cha', 'root-tea', '', '뿌리차', 'traditional Korean beverages made of roots, shoots, and barks of various plants', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Qilan tea', 'qilan-tea', '', '奇蘭', 'oolong tea from Mount Wuyi', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Rooibos', 'rooibos', '', 'rooibos', 'South Africa''s beloved ''red bush'' tea, made from the fermented leaves of Aspalathus linearis — a plant that grows exclusively in the Cederberg mountains. Naturally sweet, caffeine-free, and rich in aspalathin (a unique antioxidant found nowhere else in nature).', 'Cederberg Mountains, Western Cape, South Africa', 'tisane', 'tisane', 'none', 100, 5, 2, 'Use 1 tsp (2–3g) per 8oz (240ml) of boiling water. Steep for 5–10 minutes — unlike true teas, rooibos does not become bitter with extended steeping, only stronger. Excellent with or without milk, and naturally sweet enough to enjoy without sugar.', ARRAY['Sweet','Nutty','Earthy']::text[], ARRAY['Rich in Antioxidants','Boosts Heart Health','Lowers Cholesterol','Reduces Inflammation']::text[], '#C0856A', 40, 30, 38, 12, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ruanzhi tea', 'ruanzhi-tea', '', '軟枝', 'Variety of the tea plant processed into oolong', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Russian Caravan', 'russian-caravan', '', '', 'Blend of black teas transported to Europe by caravans', 'People''s Republic of China', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Sanyak-Cha', 'yam-tea', '', '산약차', 'beverage made by infusing yam roots', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Sayama tea', 'sayama-tea', '', '狭山茶', 'type of Japanese green tea leaves', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Sencha', 'sencha', '', '煎茶', 'Japan''s most beloved everyday green tea, accounting for nearly 80% of the country''s tea production. Grown in full sunlight and steamed immediately after harvest, Sencha has a fresh, vibrant green colour and a clean, grassy flavour with a pleasant astringency.', 'Shizuoka & Uji, Japan', 'green', 'true_tea', 'medium', 75, 2, 3, 'Use 1 tsp (roughly 3g) per 8oz (240ml) of water at 70–80°C. Steep for 1–2 minutes. Can be re-steeped up to 3 times, increasing steep time by 30 seconds each infusion. Cooler water and shorter times yield sweeter, more delicate cups.', ARRAY['Earthy','Grassy']::text[], ARRAY['Rich in Antioxidants','Improves Focus']::text[], '#7BA05B', 0, 10, 20, 25, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Shincha', 'shincha', '', '新茶', 'Japanese green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Shoumei tea', 'shoumei-tea', '', '壽眉', 'Chinese white tea', '', 'white', 'true_tea', 'low', 80, 3, 3, '', '{}'::text[], '{}'::text[], '#C8C4B0', 10, 5, 20, 10, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Shui Jin Gui tea', 'shui-jin-gui-tea', '', '水金龜', 'lighter Wuyi oolong tea', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Silver Needle (Bai Hao Yin Zhen)', 'silver-needle', '', '白毫银针', 'White Hair Silver Needle — the highest grade and most expensive white tea. Only unopened leaf buds from the Da Bai cultivar are used. Lightly oxidized, sun-withered up to 3 days. Smell of fresh-cut hay; sweet, vegetal, delicate flavor. Slightly viscous pale yellow liquor with floating white hairs. Steeping should be longer than other white teas, up to 5 minutes per brew.', 'Fujian, China', 'white', 'true_tea', 'low', 77, 5, 3, 'Use 3g per 200ml of water at 75–80°C. Steep for 3–5 minutes — white tea is forgiving and won''t turn bitter. The downy buds can be re-steeped up to 3 times. Excellent cold-brewed: 8g per litre of cold water for 8 hours in the refrigerator.', ARRAY['Floral','Sweet','Fruity']::text[], ARRAY['Rich in Antioxidants','Reduces Inflammation','Boosts Immune System']::text[], '#C8C4B0', 10, 5, 7, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Sollip-Cha', 'pine-needle-tea', '', '솔잎차', 'traditional Korean beverage made by infusing pine needles', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ssuk-Cha', 'ssuk-cha', '', '쑥차', 'traditional Korean beverage made by infusing the dried leaves of mugwort', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Sujeonggwa', 'sujeonggwa', '', '수정과', 'traditional Korean beverage made with ginger, dried persimmon, and cinnamon; often garnished with pine nuts too', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Taiping houkui', 'taiping-houkui', '', '太平猴魁', 'green tea', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tamaryokucha', 'tamaryokucha', '', '玉緑茶', 'Japanese green tea', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tencha', 'tencha', '', '碾茶', 'Japanese green tea, base of matcha', 'Japan', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tie Guan Yin (Iron Goddess of Mercy)', 'tie-guan-yin', '', '铁观音', 'Named after the Buddhist goddess of mercy, this celebrated Fujian oolong is lightly oxidised and tightly rolled into small jade-green pearls. It opens to reveal a delicate, orchid-like floral aroma with a creamy, lingering sweetness that has made it China''s favourite oolong.', 'Anxi, Fujian, China', 'oolong', 'true_tea', 'medium', 90, 3, 5, 'Use 5g per 100ml at 90–95°C. Perform a quick rinse (10 seconds) to open the tightly rolled leaves. Steep for 45–90 seconds per infusion. The tightly rolled leaves will continue to slowly unfurl over 5–7 gongfu infusions, evolving in flavour with each.', ARRAY['Floral','Creamy','Sweet']::text[], ARRAY['Rich in Antioxidants','Boosts Heart Health','Reduces Stress & Anxiety']::text[], '#D4852A', 50, 50, 45, 7, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tieguanyin', 'tieguanyin', '', '鐵觀音', 'famous oolong tea, one of top-10 Chinese teas', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tieluohan tea', 'tieluohan-tea', '', '鉄羅漢', 'type of Wuyi tea', '', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 40, 30, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tsheringma tea', 'tsheringma-tea', '', '', 'Herbal tea made in Bhutan', 'Bhutan', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tung-ting tea', 'tung-ting-tea', '', '凍頂', 'oolong from Taiwan', 'Taiwan', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Turmeric Tea', 'turmeric-tea', '', '', 'Japanese tea made from turmeric', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ureshino Tea', 'ureshino-tea', '', '嬉野茶', 'tea from the region of Ureshino, Saga Prefecture, Japan', 'Japan', 'oolong', 'true_tea', 'medium', 90, 3, 5, '', '{}'::text[], '{}'::text[], '#D4852A', 40, 30, 50, 30, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Wakoucha', 'wakoucha', '', '和紅茶', 'black tea that is produced in Japan', 'Japan', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('White Peony (Bai Mu Dan)', 'white-peony', '', '白牡丹', 'White peony tea made from one bud and two young leaves of the Da Bai cultivar. Slightly oxidized, sun-withered for 1-3 days. Mild peony and floral aroma; fruity flavor, fuller than Silver Needle but less strong than Shou Mei. Pale green or golden liquor. Best brewed with mineral water at 70-80°C.', 'Fujian, China', 'white', 'true_tea', 'low', 75, NULL, 3, 'Use 2–3g per 200ml of water at 75–85°C. Steep for 3–5 minutes. White teas are very forgiving with time. Can be re-steeped 2–3 times. A wonderful entry point into white teas — more flavourful than Silver Needle but still delicate.', ARRAY['Floral','Sweet','Fruity']::text[], ARRAY['Rich in Antioxidants','Reduces Inflammation']::text[], '#C8C4B0', 10, 5, 7, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Yesheng Bai Ya tea', 'yesheng-bai-ya-tea', '', '野生白芽', 'Chinese white tea', 'People''s Republic of China', 'white', 'true_tea', 'low', 80, 3, 3, '', '{}'::text[], '{}'::text[], '#C8C4B0', 10, 5, 20, 10, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Yingdehong tea', 'yingdehong-tea', '', '英德紅茶', 'black tea', '', 'black', 'true_tea', 'high', 95, 4, 2, '', '{}'::text[], '{}'::text[], '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Yuja-Cha', 'yuja-cha', '', '유자차', 'traditional Korean beverage made by diluting yuzu marmalade with water', '', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Yulmu-Cha', 'yulmu-cha', '', '율무차', 'beverage made with the flour of roasted grains of Job''s tears', 'Korea', 'tisane', 'tisane', 'none', 100, 5, 2, '', '{}'::text[], '{}'::text[], '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Zhuyeqing Tea', 'zhuyeqing-tea', '', '竹叶青茶', 'bamboo leaf green tea', '', 'green', 'true_tea', 'medium', 75, 2, 3, '', '{}'::text[], '{}'::text[], '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL);
ON CONFLICT (slug) DO UPDATE SET
  phonetic_name = EXCLUDED.phonetic_name,
  original_name = EXCLUDED.original_name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  brewing_num_brews = EXCLUDED.brewing_num_brews,
  brewing_instructions = EXCLUDED.brewing_instructions,
  health_benefits = EXCLUDED.health_benefits,
  color_hex = EXCLUDED.color_hex,
  oxidation_level = EXCLUDED.oxidation_level,
  roast_level = EXCLUDED.roast_level,
  flavor_x = EXCLUDED.flavor_x,
  flavor_y = EXCLUDED.flavor_y,
  source_type = 'default',
  source = 'Teapp',
  is_public = TRUE;

-- Migrate existing custom_teas into teas table, then drop custom_teas
INSERT INTO teas (name, slug, description, tea_type, origin, caffeine_level, brewing_temp_c, brewing_time_min, characteristics, source_type, source, owner_id, is_public)
SELECT name, slug, description, tea_type, origin, caffeine_level,
  brewing_temp_c::int, brewing_time_min::int, characteristics,
  'user', 'custom', user_id, FALSE
FROM custom_teas
ON CONFLICT (slug) DO NOTHING;

-- Update user_teas: custom tea references now point to teas table
UPDATE user_teas ut
SET tea_id = (SELECT id FROM teas t WHERE t.slug = (SELECT slug FROM custom_teas ct WHERE ct.id = ut.tea_id))
WHERE tea_id NOT IN (SELECT id FROM teas);

-- Update tea_logs: custom tea references now point to teas table
UPDATE tea_logs tl
SET tea_id = (SELECT id FROM teas t WHERE t.slug = (SELECT slug FROM custom_teas ct WHERE ct.id = tl.tea_id))
WHERE tea_id NOT IN (SELECT id FROM teas);

-- Drop custom_teas table
DROP TABLE IF EXISTS custom_teas;

-- Add accent_color to user_preferences
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#c4853f';
