-- Migration: Seed 123 default teas from teas.ts
-- All teas get source_type='default', source='Teapp', is_public=TRUE, owner_id=NULL

-- First, add new columns to teas table
ALTER TABLE teas ADD COLUMN IF NOT EXISTS source_type TEXT DEFAULT 'default' CHECK (source_type IN ('default', 'user', 'teahouse'));
ALTER TABLE teas ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'Teapp';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT TRUE;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS phonetic_name TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS original_name TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS brewing_num_brews INT DEFAULT 1;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS brewing_instructions TEXT DEFAULT '';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS health_benefits TEXT[] DEFAULT '{}';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS color_hex TEXT DEFAULT '#999';
ALTER TABLE teas ADD COLUMN IF NOT EXISTS oxidation_level INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS roast_level INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS flavor_x INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS flavor_y INT DEFAULT 50;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS wikidata_qid TEXT;
ALTER TABLE teas ADD COLUMN IF NOT EXISTS caffeine_level TEXT DEFAULT 'medium';

UPDATE teas SET source_type = 'default', source = 'Teapp', is_public = TRUE WHERE source_type IS NULL OR source_type = 'default';

-- Insert 123 default teas (ON CONFLICT on slug DO NOTHING if already exists)
-- Using a single transaction
INSERT INTO teas (name, slug, phonetic_name, original_name, description, origin, tea_type, category, caffeine_level, brewing_temp_c, brewing_time_min, brewing_num_brews, brewing_instructions, characteristics, health_benefits, color_hex, oxidation_level, roast_level, flavor_x, flavor_y, source_type, source, owner_id, is_public, wikidata_qid) VALUES
  ('Sencha', 'sencha', '', '煎茶', 'Japan''s most beloved everyday green tea, accounting for nearly 80% of the country''s tea production. Grown in full sunlight and steamed immediately after harvest, Sencha has a fresh, vibrant green colour and a clean, grassy flavour with a pleasant astringency.', 'Shizuoka & Uji, Japan', 'green', 'True Tea', 'medium', 75, 2, 3, 'Use 1 tsp (roughly 3g) per 8oz (240ml) of water at 70–80°C. Steep for 1–2 minutes. Can be re-steeped up to 3 times, increasing steep time by 30 seconds each infusion. Cooler water and shorter times yield sweeter, more delicate cups.', ARRAY['Earthy','Grassy'], ARRAY['Rich in Antioxidants','Improves Focus'], '#7BA05B', 0, 10, 20, 25, 'default', 'Teapp', NULL, TRUE, 'Q1334390'),
  ('Earl Grey', 'earl-grey', '', '', 'The world''s most recognisable flavoured tea — a classic black tea blend naturally scented with bergamot oil, named after the British Prime Minister Charles Grey. Its floral citrus fragrance is immediately distinctive.', 'United Kingdom', 'blend', 'Blend', 'high', 95, 4, 1, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–5 minutes depending on strength preference. Excellent with a splash of milk or a slice of lemon. Avoid boiling water to preserve the bergamot''s delicate aroma.', ARRAY['Citrusy','Bold'], ARRAY['Rich in Antioxidants','Boosts Heart Health'], '#B07D56', 40, 30, 43, 40, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Chamomile Mint', 'chamomile-mint', '', '', 'A soothing herbal infusion blending calming chamomile with refreshing peppermint. The gentle sweetness of chamomile flowers balances the cooling menthol of peppermint for a tisane that is both relaxing and invigorating.', 'Egypt / United States', 'tisane', 'Tisane (Herbal Tea)', 'none', 100, 5, 2, 'Use 1.5 tsp (3–4g) per 8oz (240ml) of boiling water. Steep covered for 5 minutes to trap the essential oils. The blend is forgiving — longer steeping intensifies without becoming bitter. Add honey to enhance sweetness.', ARRAY['Floral','Minty'], ARRAY['Promotes Sleep & Relaxation','Aids Digestion'], '#C0856A', 40, 30, 12, 10, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gyokuro', 'gyokuro', '', '玉露', 'Japan''s most prized green tea, shaded from sunlight for 20+ days before harvest. The reduced light signals the plant to produce extraordinary levels of L-theanine and chlorophyll, resulting in an intensely umami, sweet, and deeply complex cup known as ''jade dew''.', 'Uji & Yame, Japan', 'green', 'True Tea', 'high', 60, 2, 3, 'Use 5g per 150ml of water at 55–60°C — far cooler than any other tea. Steep for exactly 2 minutes without stirring. The low temperature extracts sweetness and umami while suppressing bitterness. Re-steep 2–3 times, slightly increasing temperature each time.', ARRAY['Umami','Sweet','Grassy'], ARRAY['Rich in Antioxidants','Improves Focus','Boosts Heart Health','Rich in L-Theanine'], '#7BA05B', 0, 10, 5, 5, 'default', 'Teapp', NULL, TRUE, 'Q1424874'),
  ('Matcha', 'matcha', '', '抹茶', 'A finely stone-ground powder made from shade-grown tencha leaves. Unlike all other teas, matcha is whisked into water rather than steeped — meaning you consume the entire leaf and all its nutrients. One of the most antioxidant-rich foods on earth.', 'Uji, Japan', 'green', 'True Tea', 'high', 80, 1, 3, 'Sift 1–2g of ceremonial grade matcha into a warmed bowl. Add 70–80ml of water at 75–80°C (never boiling). Whisk vigorously in a ''W'' or ''M'' motion until frothy. For usucha (thin tea) use 1g; for koicha (thick tea) use 3–4g and whisk slowly.', ARRAY['Umami','Grassy','Vegetal','Creamy'], ARRAY['Rich in Antioxidants','Improves Focus','Supports Weight Management','Reduces Stress & Anxiety'], '#7BA05B', 0, 10, 5, 5, 'default', 'Teapp', NULL, TRUE, 'Q822331'),
  ('Dragonwell (Long Jing)', 'dragonwell-long-jing', '', '龙井', 'China''s most celebrated green tea, named for a well in the hills of Hangzhou. Pan-fired in a hot wok to create its signature flat, sword-shaped leaves, Dragonwell has a clean chestnut sweetness, delicate vegetal notes, and a lingering finish prized by emperors for centuries.', 'Hangzhou, Zhejiang, China', 'green', 'True Tea', 'medium', 80, 2, 3, 'Use 3g per 200ml of water at 75–80°C. Steep for 1–2 minutes. The second and third infusions are often considered the most flavourful. Use a glass cup to watch the leaves unfurl — part of the traditional Dragonwell experience.', ARRAY['Grassy','Nutty','Sweet'], ARRAY['Rich in Antioxidants','Improves Focus','Boosts Heart Health'], '#7BA05B', 0, 10, 13, 7, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Gunpowder Green', 'gunpowder-green', '', '珠茶', 'Named for its tightly rolled pellets that resemble old musket powder, this bold Chinese green tea from Zhejiang province unfurls dramatically in hot water. Its robust, slightly smoky character makes it one of the longest-lasting green teas in storage.', 'Zhejiang, China', 'green', 'True Tea', 'medium', 80, 3, 3, 'Use 1 tsp (3g) of pellets per 8oz (240ml) of water at 75–80°C. Steep for 2–3 minutes. Overbrewing will intensify bitterness. The traditional base for Moroccan Mint Tea — the pellets hold up well to the addition of sugar and mint.', ARRAY['Smoky','Bold','Earthy'], ARRAY['Rich in Antioxidants','Boosts Immune System'], '#7BA05B', 0, 10, 50, 40, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Silver Needle (Bai Hao Yin Zhen)', 'silver-needle', '', '白毫银针', 'The most prized of all white teas, made exclusively from young, silver-downy, unopened buds harvested during a brief spring window in Fujian. Ethereally light and sweet with a subtle floral complexity — the result of the most delicate processing of any tea.', 'Fujian, China', 'white', 'True Tea', 'low', 80, 4, 3, 'Use 3g per 200ml of water at 75–80°C. Steep for 3–5 minutes — white tea is forgiving and won''t turn bitter. The downy buds can be re-steeped up to 3 times. Excellent cold-brewed: 8g per litre of cold water for 8 hours in the refrigerator.', ARRAY['Floral','Sweet','Fruity'], ARRAY['Rich in Antioxidants','Reduces Inflammation','Boosts Immune System'], '#C8C4B0', 10, 5, 7, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('White Peony (Bai Mu Dan)', 'white-peony', '', '白牡丹', 'The most popular white tea in China, crafted from one bud and two young leaves of Camellia sinensis. Bai Mu Dan offers a fuller body and slightly bolder flavour than Silver Needle while retaining the characteristic delicate sweetness of white tea processing.', 'Fujian, China', 'white', 'True Tea', 'low', 80, 3, 3, 'Use 2–3g per 200ml of water at 75–85°C. Steep for 3–5 minutes. White teas are very forgiving with time. Can be re-steeped 2–3 times. A wonderful entry point into white teas — more flavourful than Silver Needle but still delicate.', ARRAY['Floral','Sweet','Fruity'], ARRAY['Rich in Antioxidants','Reduces Inflammation'], '#C8C4B0', 10, 5, 7, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Darjeeling', 'darjeeling', '', '', 'Often called the ''Champagne of Teas'', Darjeeling is grown in the misty Himalayan foothills of West Bengal at elevations up to 2,000m. Its famous muscatel character — a musky, grape-like sweetness — is unique in the tea world and protected by geographical indication.', 'Darjeeling, West Bengal, India', 'black', 'True Tea', 'high', 90, 3, 2, 'First flush: use water at 85–90°C and steep 2–3 minutes. Second flush: 90–95°C for 3–4 minutes. Best enjoyed without milk for first flush to appreciate the muscatel notes. Second flush pairs well with a splash of milk.', ARRAY['Floral','Fruity','Malty'], ARRAY['Rich in Antioxidants','Boosts Heart Health','Improves Focus'], '#8B4513', 90, 70, 62, 40, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Assam', 'assam', '', '', 'Grown in the lush Brahmaputra river valley of northeastern India — the world''s largest tea-growing region. Assam is a robust, full-bodied black tea with a bold malty character, deep amber liquor, and the backbone of most classic British breakfast blends.', 'Assam, India', 'black', 'True Tea', 'high', 95, 4, 2, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–5 minutes. Assam stands up beautifully to milk and sugar. The foundation of English Breakfast and Irish Breakfast blends. CTC (crush-tear-curl) Assam brews faster and stronger than whole-leaf.', ARRAY['Bold','Malty','Earthy'], ARRAY['Rich in Antioxidants','Improves Energy Levels','Boosts Heart Health'], '#8B4513', 90, 70, 85, 65, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ceylon', 'ceylon', '', '', 'Sri Lanka''s flagship black tea, named for the island''s colonial-era name. Grown across multiple high-altitude regions, Ceylon teas are known for their bright amber liquor, brisk character, and distinctive notes of citrus, cocoa, and spice with 50–90mg of caffeine per cup.', 'Sri Lanka', 'black', 'True Tea', 'high', 95, 4, 2, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–4 minutes. Excellent with or without milk. Uva region teas (high altitude) have the most distinctive spicy character; Nuwara Eliya produces a lighter, more delicate cup.', ARRAY['Bold','Citrusy','Malty'], ARRAY['Rich in Antioxidants','Improves Focus','Boosts Heart Health'], '#8B4513', 90, 70, 73, 55, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lapsang Souchong', 'lapsang-souchong', '', '正山小種', 'The world''s first black tea, originating from the Wuyi Mountains in 1646. Its large leaves are withered and dried over smouldering pine wood fires, absorbing an intensely smoky, resinous character that has earned it the nickname ''the whiskey of black teas''.', 'Wuyi Mountains, Fujian, China', 'black', 'True Tea', 'medium', 95, 3, 2, 'Use 2g per 200ml of water at 90–95°C. Steep for 3–4 minutes. Avoid over-steeping to prevent bitterness. Best enjoyed without milk to fully appreciate the smoke. An acquired taste — loved passionately by those who appreciate it.', ARRAY['Smoky','Bold','Woody'], ARRAY['Rich in Antioxidants','Reduces Inflammation','Aids Digestion'], '#8B4513', 90, 70, 92, 65, 'default', 'Teapp', NULL, TRUE, 'Q634871'),
  ('Da Hong Pao (Big Red Robe)', 'da-hong-pao', '', '大红袍', 'One of China''s most legendary teas, grown on the mineral-rich volcanic cliffs of the UNESCO World Heritage Wuyi Mountains. A heavily roasted, complex oolong with layers of stone fruit, roasted caramel, and lingering floral notes that can be re-steeped many times.', 'Wuyi Mountains, Fujian, China', 'oolong', 'True Tea', 'medium', 95, 3, 5, 'Gongfu style: use 5g per 100ml at 95°C. Rinse once for 10 seconds (discard this wash). First infusion: 45 seconds. Add 15–30 seconds per subsequent infusion. Excellent for 6–8 infusions. Western style: 3g per 200ml, 3–4 minutes.', ARRAY['Earthy','Smoky','Fruity','Sweet'], ARRAY['Rich in Antioxidants','Boosts Heart Health','Aids Digestion'], '#D4852A', 50, 50, 67, 25, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Tie Guan Yin (Iron Goddess of Mercy)', 'tie-guan-yin', '', '铁观音', 'Named after the Buddhist goddess of mercy, this celebrated Fujian oolong is lightly oxidised and tightly rolled into small jade-green pearls. It opens to reveal a delicate, orchid-like floral aroma with a creamy, lingering sweetness that has made it China''s favourite oolong.', 'Anxi, Fujian, China', 'oolong', 'True Tea', 'medium', 90, 3, 5, 'Use 5g per 100ml at 90–95°C. Perform a quick rinse (10 seconds) to open the tightly rolled leaves. Steep for 45–90 seconds per infusion. The tightly rolled leaves will continue to slowly unfurl over 5–7 gongfu infusions, evolving in flavour with each.', ARRAY['Floral','Creamy','Sweet'], ARRAY['Rich in Antioxidants','Boosts Heart Health','Reduces Stress & Anxiety'], '#D4852A', 50, 50, 45, 7, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Pu-erh', 'pu-erh', '', '普洱', 'An aged, post-fermented tea from Yunnan province with over 2,000 years of history, the only tea category that actively improves with age. Shou (ripe) pu-erh is earthy, smooth, and rich; sheng (raw) pu-erh is more complex and evolves over decades like a fine wine.', 'Yunnan, China', 'pu-erh', 'True Tea', 'medium', 100, 4, 8, 'Always rinse first: pour boiling water over 5g of pu-erh per 150ml, steep 10 seconds, discard. This opens the aged leaves. Then steep 30–60 seconds for gongfu style, or 3–4 minutes Western style. Can yield 6–10 or more infusions.', ARRAY['Earthy','Smoky','Bold','Nutty'], ARRAY['Lowers Cholesterol','Boosts Heart Health','Aids Digestion','Supports Weight Management'], '#6B4226', 100, 90, 95, 72, 'default', 'Teapp', NULL, TRUE, NULL),
  ('English Breakfast', 'english-breakfast', '', '', 'The quintessential British morning tea — a robust, full-bodied blend of Assam, Ceylon, and Darjeeling black teas, designed to be paired with milk, hold its own against a hearty breakfast, and provide a strong caffeine start to the day.', 'United Kingdom', 'blend', 'Blend', 'high', 95, 4, 1, 'Use 1 tsp (2–3g) per 8oz (240ml) of near-boiling water. Steep for 3–4 minutes. Traditionally served with whole milk added to the cup first, then tea poured over. Sugar is optional. The ratio of teas in the blend varies by producer.', ARRAY['Bold','Malty'], ARRAY['Rich in Antioxidants','Improves Energy Levels','Improves Focus'], '#B07D56', 40, 30, 53, 50, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Masala Chai', 'masala-chai', '', 'चाय', 'India''s beloved spiced tea, brewed strong with milk and a warming blend of cardamom, ginger, cinnamon, cloves, and black pepper. Deeply aromatic, invigorating, and comforting — masala chai is as much a ritual as a beverage, sold on every street corner in India.', 'India', 'blend', 'Blend', 'high', 100, 5, 1, 'Simmer 1 tsp (2–3g) of strong black tea with 200ml of water and 200ml of whole milk. Crush and add spices: 3–4 cardamom pods, a cinnamon stick, 3 cloves, 2 slices of ginger, and 3–4 black peppercorns. Bring to a boil twice. Strain and sweeten with jaggery or sugar.', ARRAY['Spicy','Sweet','Malty','Creamy'], ARRAY['Aids Digestion','Improves Energy Levels','Boosts Immune System','Reduces Inflammation'], '#B07D56', 40, 30, 53, 27, 'default', 'Teapp', NULL, TRUE, 'Q877661'),
  ('Jasmine Green Tea', 'jasmine-green', '', '茉莉花茶', 'China''s most aromatic tea, crafted by layering freshly harvested jasmine blossoms over green tea leaves for several nights, allowing the leaves to absorb the fragrance naturally. The result is a delicate, perfumed cup that is simultaneously floral and refreshing.', 'Fujian & Guangxi, China', 'blend', 'Blend', 'medium', 80, 2, 1, 'Use 2g per 200ml of water at 80–85°C. Steep for 2–3 minutes. Never use boiling water — it damages the delicate jasmine aroma. Excellent for 2–3 infusions. Jasmine pearls (a rolled variety) are especially beautiful to watch unfurl in a glass cup.', ARRAY['Floral','Sweet','Grassy'], ARRAY['Rich in Antioxidants','Reduces Stress & Anxiety','Promotes Sleep & Relaxation'], '#B07D56', 40, 30, 20, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Moroccan Mint Tea', 'moroccan-mint', '', '', 'The cornerstone of North African hospitality, this vibrant blend of gunpowder green tea and fresh spearmint is traditionally poured from a great height into ornate glasses to create a froth. Sweet, minty, and deeply refreshing — serving it to a guest is an act of welcome.', 'Morocco, North Africa', 'blend', 'Blend', 'medium', 100, 5, 1, 'Steep 1 tsp (3g) of gunpowder green in boiling water for 1 minute, then discard this bitterness-removing first steep. Refill the pot with boiling water, add a generous handful of fresh spearmint and sugar (traditionally 2–3 tsp). Steep 5 minutes. Pour from height to aerate.', ARRAY['Minty','Sweet','Refreshing'], ARRAY['Aids Digestion','Boosts Immune System','Rich in Antioxidants'], '#B07D56', 40, 30, 17, 15, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Rooibos', 'rooibos', '', 'rooibos', 'South Africa''s beloved ''red bush'' tea, made from the fermented leaves of Aspalathus linearis — a plant that grows exclusively in the Cederberg mountains. Naturally sweet, caffeine-free, and rich in aspalathin (a unique antioxidant found nowhere else in nature).', 'Cederberg Mountains, Western Cape, South Africa', 'tisane', 'Tisane (Herbal Tea)', 'none', 100, 5, 2, 'Use 1 tsp (2–3g) per 8oz (240ml) of boiling water. Steep for 5–10 minutes — unlike true teas, rooibos does not become bitter with extended steeping, only stronger. Excellent with or without milk, and naturally sweet enough to enjoy without sugar.', ARRAY['Sweet','Nutty','Earthy'], ARRAY['Rich in Antioxidants','Boosts Heart Health','Lowers Cholesterol','Reduces Inflammation'], '#C0856A', 40, 30, 38, 12, 'default', 'Teapp', NULL, TRUE, 'Q56342268'),
  ('Hibiscus', 'hibiscus', '', '', 'A vibrant ruby-red tisane brewed from the dried calyces of Hibiscus sabdariffa, known for its brilliant colour and tart, cranberry-like flavour. Packed with vitamin C and anthocyanins, hibiscus is one of the most visually striking and health-supporting teas in the world.', 'Egypt, Mexico & West Africa', 'tisane', 'Tisane (Herbal Tea)', 'none', 100, 5, 2, 'Use 1–2 tsp (2–4g) of dried flowers per 8oz (240ml) of boiling water. Steep for 5–7 minutes for maximum colour and flavour. Excellent served iced — refrigerate after brewing. Add honey or a cinnamon stick to balance the tartness. Known as ''karkadé'' in Egypt and ''agua de jamaica'' in Mexico.', ARRAY['Tart','Fruity','Floral'], ARRAY['Rich in Antioxidants','Boosts Heart Health','Reduces Inflammation','Boosts Immune System'], '#C0856A', 40, 30, 17, 10, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Peppermint', 'peppermint', '', '', 'A crisp, cooling tisane made from the dried leaves of Mentha piperita — a natural hybrid of spearmint and watermint. One of the world''s most popular herbal teas, prized for its intensely clean menthol character, digestive benefits, and invigorating clarity.', 'Europe & North America', 'tisane', 'Tisane (Herbal Tea)', 'none', 100, 5, 2, 'Use 1–2 tsp (2–4g) of dried peppermint per 8oz (240ml) of boiling water. Steep covered for 5–7 minutes to trap the volatile menthol oils. Fresh peppermint leaves can be substituted — use 2–3 times the quantity. Peppermint does not turn bitter with extended steeping.', ARRAY['Minty','Sweet','Grassy','Refreshing'], ARRAY['Aids Digestion','Reduces Stress & Anxiety','Boosts Immune System'], '#C0856A', 40, 30, 5, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Ginger Root', 'ginger-root', '', '', 'A warming and invigorating tisane brewed from dried slices of Zingiber officinale root. Sharp, fiery, and deeply aromatic, ginger tea has been used in traditional Ayurvedic and Chinese medicine for millennia as a remedy for nausea, poor digestion, and inflammation.', 'India, China & Caribbean', 'tisane', 'Tisane (Herbal Tea)', 'none', 100, 5, 2, 'Use 1 tsp (2–3g) of dried ginger root per 8oz (240ml) of boiling water. Steep for 5–10 minutes — longer brewing creates more heat. For fresh ginger, use 3–4 thin slices and simmer for 10 minutes. Add honey and a squeeze of fresh lemon to round out the spice beautifully.', ARRAY['Spicy','Sweet','Earthy'], ARRAY['Aids Digestion','Reduces Inflammation','Boosts Immune System','Improves Energy Levels'], '#C0856A', 40, 30, 35, 20, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Lavender', 'lavender', '', '', 'A soothing floral tisane brewed from the dried buds of Lavandula angustifolia. With a delicate, perfumed sweetness and an unmistakable calming aroma, lavender tea has long been treasured in European herbal traditions as an aid to anxiety, insomnia, and restlessness.', 'Provence, France & Mediterranean', 'tisane', 'Tisane (Herbal Tea)', 'none', 95, 5, 2, 'Use 1 tsp (1–2g) of dried lavender buds per 8oz (240ml) of water at 90–95°C (avoid boiling — it can make lavender medicinal). Steep for 5 minutes. Pairs beautifully with honey or a slice of lemon. Excellent blended with chamomile for a deeper sleep-promoting effect.', ARRAY['Floral','Sweet','Creamy'], ARRAY['Promotes Sleep & Relaxation','Reduces Stress & Anxiety','Reduces Inflammation'], '#C0856A', 40, 30, 20, 5, 'default', 'Teapp', NULL, TRUE, NULL),
  ('Junshan Yinzhen', 'junshan-yinzhen', '', '君山銀針;', 'One of China''s Ten Famous Teas and the most celebrated yellow tea in the world. Harvested exclusively from Junshan Island on Dongting Lake in Hunan, each batch uses only the tenderest first-flush buds plucked in a brief spring window. The distinctive sealed yellowing step (闷黄, mén huáng) gently mellows the leaves, yielding a cup that sits between green and white tea — less grassy than the former, with more body than the latter. Expect mellow sweetness, light grain, a whisper of apricot, and a clean lingering finish.', 'Junshan Island, Hunan, China', 'yellow', 'True Tea', 'low', 70, 3, 3, 'Use 3g per 150ml of water at 70–75°C — avoid boiling water, which will mask the subtle sweetness. Steep for 2–3 minutes. Use a glass vessel if possible to watch the silver needle buds dance upright as they unfurl. Can be re-steeped 2–3 times, each infusion revealing slightly different notes.', ARRAY['Sweet','Grassy','Floral','Nutty'], ARRAY['Rich in Antioxidants','Aids Digestion','Reduces Inflammation','Boosts Immune System'], '#E6C84E', 15, 15, 18, 5, 'default', 'Teapp', NULL, TRUE, 'Q1070040'),
  ('Brown Rice Tea', 'brown-rice-tea', '', '玄米茶', 'beverage made by infusing roasted brown rice grains', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q1074092'),
  ('Corn Tea', 'corn-tea', '', '옥수수차', 'beverage made by infusing roasted corn kernels', 'South Korea', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q1195324'),
  ('Hojicha', 'hojicha', '', '焙じ茶', 'Japanese green tea roasted over charcoal', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q1652744'),
  ('Kabuse Tea', 'kabuse-tea', '', 'かぶせ茶', 'Japanese shade grown green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q1720874'),
  ('Konacha', 'konacha', '', '粉茶', 'lower-grade Japanese green tea made up of small leaves and teadust', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q1781131'),
  ('Kukicha', 'kukicha', '', '茎茶', 'Japanese tea blend', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 40, 30, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q1791365'),
  ('Tamaryokucha', 'tamaryokucha', '', '玉緑茶', 'Japanese green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q2596949'),
  ('Fukuju', 'fukuju', '', '福寿', 'type of green tea', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q3090697'),
  ('Kamairicha tea', 'kamairicha-tea', '', '釜炒り茶', 'Japanese green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q4210698'),
  ('24 Flavors', '24-flavors', '', '二十四味', 'Cantonese herbal tea', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q4631922'),
  ('Dafang tea', 'dafang-tea', '', '頂谷大方', 'Flat green tea from Anhui province (China), similar to Longjing', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q5208302'),
  ('Kohki Tea', 'kohki-tea', '', '', 'Japanese herbal drink very high in antioxidant activity', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q6426017'),
  ('Arrowroot Tea', 'arrowroot-tea', '', '', 'beverage made by infusing arrowroot roots', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q6449330'),
  ('Mecha tea', 'mecha-tea', '', '芽茶', 'Popular after-dinner Japanese green tea', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q6804456'),
  ('Mengding Ganlu tea', 'mengding-ganlu-tea', '', '蒙頂甘露', 'Chinese green tea with sweet aftertaste', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q6816973'),
  ('Taiping houkui', 'taiping-houkui', '', '太平猴魁', 'green tea', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q10036993'),
  ('Buckwheat Tea', 'buckwheat-tea', '', '메밀차', 'beverage made by infusing roasted buckwheat grains', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q11270489'),
  ('Fukamushicha', 'fukamushicha', '', '深蒸し茶', 'kind of green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q11560264'),
  ('Tencha', 'tencha', '', '碾茶', 'Japanese green tea, base of matcha', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q11587820'),
  ('Huoshan Huangya tea', 'huoshan-huangya-tea', '', '霍山黄芽', 'yellow tea from Anhui province', 'People''s Republic of China', 'yellow', '', '', 80, 2, 3, '', '{}', '{}', '#E6C84E', 15, 15, 30, 18, 'default', 'Teapp', NULL, TRUE, 'Q13636901'),
  ('Goishicha', 'goishicha', '', '碁石茶', 'type of fermented tea', '', 'pu-erh', '', '', 95, 4, 8, '', '{}', '{}', '#6B4226', 40, 30, 78, 55, 'default', 'Teapp', NULL, TRUE, 'Q25113097'),
  ('Persimmon Leaf Tea', 'persimmon-leaf-tea', '', '감잎차', 'traditional Korean beverage made by infusing dried leaves of persimmon', 'Korea', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q29944733'),
  ('Pine Needle Tea', 'pine-needle-tea', '', '', 'traditional Korean beverage made by infusing pine needles', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30043825'),
  ('Doncha', 'doncha', '', '돈차', 'Korean coin-shaped post-fermented tea', 'Korea', 'pu-erh', '', '', 95, 4, 8, '', '{}', '{}', '#6B4226', 40, 30, 78, 55, 'default', 'Teapp', NULL, TRUE, 'Q30043860'),
  ('Plum Blossom Tea', 'plum-blossom-tea', '', '', 'traditional Korean beverage made by infusing the dried plum flowers', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30043919'),
  ('Maesil-Cha', 'maesil-cha', '', '매실차', 'traditional Korean beverage made by diluting the maesil marmalade with water', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30595699'),
  ('Yam Tea', 'yam-tea', '', '', 'beverage made by infusing yam roots', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q55729572'),
  ('Meng Ding Huangya', 'meng-ding-huangya', '', '蒙顶黄芽', 'yellow tea from Mt. Meng', '', 'yellow', '', '', 80, 2, 3, '', '{}', '{}', '#E6C84E', 15, 15, 30, 18, 'default', 'Teapp', NULL, TRUE, 'Q106333717'),
  ('Zhuyeqing Tea', 'zhuyeqing-tea', '', '竹叶青茶', 'bamboo leaf green tea', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q106365726'),
  ('Asamushi', 'asamushi', '', '浅蒸し', 'type of sencha green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q124606582'),
  ('Irimushi', 'irimushi', '', '炒蒸し', 'type of sencha green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q124606580'),
  ('Chūmushi', 'chūmushi', '', '中蒸し', 'type of sencha green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q124606581'),
  ('Dian Hong Jin Luo', 'dian-hong-jin-luo', '', '滇红金螺', 'Type of Chinese black tea', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q125514331'),
  ('Duyun Maojian', 'duyun-maojian', '', '都匀毛尖', 'Chinese Green Tea Type', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q134705664'),
  ('Sujeonggwa', 'sujeonggwa', '', '수정과', 'traditional Korean beverage made with ginger, dried persimmon, and cinnamon; often garnished with pine nuts too', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q39553'),
  ('Genmaicha', 'genmaicha', '', '玄米茶', 'Japanese green tea mixed with brown rice', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q519365'),
  ('Ogwa-Cha', 'ogwa-cha', '', '오과차', 'five-fruit tea', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q595559'),
  ('Russian Caravan', 'russian-caravan', '', '', 'Blend of black teas transported to Europe by caravans', 'People''s Republic of China', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q604976'),
  ('Tung-ting tea', 'tung-ting-tea', '', '凍頂', 'oolong from Taiwan', 'Taiwan', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q697016'),
  ('Chrysanthemum Tea', 'chrysanthemum-tea', '', '菊花茶', 'beverage made by infusing dried flowers of chrysanthemum', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q708203'),
  ('Bancha', 'bancha', '', '番茶', 'Japanese green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q789960'),
  ('Maghrebi mint tea', 'maghrebi-mint-tea', '', 'أتاي', 'tea preparation and form of tea consumption in the Maghreb countries', 'Maghreb', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q937101'),
  ('Lady Grey', 'lady-grey', '', '', 'trademarked variation on Earl Grey tea', 'England', 'blend', '', '', 90, 4, 1, '', '{}', '{}', '#B07D56', 40, 30, 40, 35, 'default', 'Teapp', NULL, TRUE, 'Q1156522'),
  ('Tieguanyin', 'tieguanyin', '', '鐵觀音', 'famous oolong tea, one of top-10 Chinese teas', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q1328947'),
  ('Keemun', 'keemun', '', '祁門紅茶', 'famous Chinese black tea', 'People''s Republic of China', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q1376140'),
  ('Shincha', 'shincha', '', '新茶', 'Japanese green tea', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q1471207'),
  ('Lapacho', 'lapacho', '', '', 'herbal tea made from a Central and South American tree''s bark', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q1828662'),
  ('East Friesland tea blend', 'east-friesland-tea-blend', '', 'Ostfriesentee', 'black tea, blend of East Friesland', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q2035490'),
  ('Baozhong', 'baozhong', '', '包種茶', 'famous Taiwan spring tea between green and oolong', 'Taiwan', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q2106693'),
  ('Yingdehong tea', 'yingdehong-tea', '', '英德紅茶', 'black tea', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q2908881'),
  ('Biluochun', 'biluochun', '', '碧螺春', 'famous Chinese green tea from Dongting Mountains, near Suzhou', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q2983740'),
  ('Dianhong', 'dianhong', '', '滇紅茶', 'type of Chinese black tea grown in Yunnan province', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q2992098'),
  ('Jin Fo tea', 'jin-fo-tea', '', '金佛茶', 'medium Wuyi Oolong tea', 'People''s Republic of China', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q3179181'),
  ('Tsheringma tea', 'tsheringma-tea', '', '', 'Herbal tea made in Bhutan', 'Bhutan', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q4513001'),
  ('Shoumei tea', 'shoumei-tea', '', '壽眉', 'Chinese white tea', '', 'white', '', '', 80, 3, 3, '', '{}', '{}', '#C8C4B0', 10, 5, 20, 10, 'default', 'Teapp', NULL, TRUE, 'Q4526292'),
  ('Bai Jiguan tea', 'bai-jiguan-tea', '', '白雞冠', 'Well-known oolong tea of Wuyi', 'China', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q4843134'),
  ('Ban Tian Yao tea', 'ban-tian-yao-tea', '', '半天腰', 'A rarely seen Mount Wuyi Oolong with a light smokey taste', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q4853724'),
  ('Bu Zhi Chun tea', 'bu-zhi-chun-tea', '', '不知春', 'a rarely seen Mount Wuyi Oolong with a light taste', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q4982075'),
  ('Daechu-Cha', 'daechu-cha', '', '대추차', 'traditional Korean beverage made by infusing dried jujube berries', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q5208153'),
  ('Dongfang meiren tea', 'dongfang-meiren-tea', '', '東方美人', 'oolong tea', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q5295867'),
  ('Mogwa-Cha', 'mogwa-cha', '', '모과차', 'traditional Korean beverage made by diluting the mogwa marmalade with water', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q5358446'),
  ('Fo Shou tea', 'fo-shou-tea', '', '佛手', 'A rarely seen Mount Wuyi Oolong', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q5463781'),
  ('Golden Monkey tea', 'golden-monkey-tea', '', '金猴茶', 'a fine black tea from Yunnan province', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q5579671'),
  ('Goji Tea', 'goji-tea', '', '枸杞茶', 'traditional Korean and Chinese beverage made by infusing dried goji berries or leaves', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q5615230'),
  ('High mountain tea', 'high-mountain-tea', '', '高山茶', 'varieties of oolong tea grown in Taiwan', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q5757613'),
  ('Huang Guanyin tea', 'huang-guanyin-tea', '', '黄觀音茶', 'A new cultivar of Mount Wuyi Oolong', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q5925527'),
  ('Huang Mei Gui tea', 'huang-mei-gui-tea', '', '黃玫瑰', 'a very new Wuyi Oolong tea', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q5925624'),
  ('Huangjin Gui', 'huangjin-gui', '', '黃金桂', 'premium variety of Oolong from Anxi', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q5925951'),
  ('Ginseng Tea', 'ginseng-tea', '', '人参茶', 'beverage made by infusing ginseng roots', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q6037041'),
  ('Jin Xuan tea', 'jin-xuan-tea', '', '金萱', 'Taiwanese oolong tea', 'Taiwan', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q6201947'),
  ('Qilan tea', 'qilan-tea', '', '奇蘭', 'oolong tea from Mount Wuyi', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q7267739'),
  ('Rougui tea', 'rougui-tea', '', '肉桂茶', 'variety of the tea plant from Wuyi Moutains', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 40, 30, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q7370926'),
  ('Ruanzhi tea', 'ruanzhi-tea', '', '軟枝', 'Variety of the tea plant processed into oolong', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q7375720'),
  ('Sayama tea', 'sayama-tea', '', '狭山茶', 'type of Japanese green tea leaves', 'Japan', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q7429107'),
  ('Shui Xian', 'shui-xian', '', '水仙', 'variety of the tea tree and Chinese oolong tea', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q7504735'),
  ('Shui Jin Gui tea', 'shui-jin-gui-tea', '', '水金龜', 'lighter Wuyi oolong tea', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 50, 50, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q7504737'),
  ('Tieluohan tea', 'tieluohan-tea', '', '鉄羅漢', 'type of Wuyi tea', '', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 40, 30, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q7801005'),
  ('Turmeric Tea', 'turmeric-tea', '', '', 'Japanese tea made from turmeric', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q7878345'),
  ('Maojian tea', 'maojian-tea', '', '信陽毛尖', 'one of the top Chinese green teas', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q10888066'),
  ('Ureshino Tea', 'ureshino-tea', '', '嬉野茶', 'tea from the region of Ureshino, Saga Prefecture, Japan', 'Japan', 'oolong', '', '', 90, 3, 5, '', '{}', '{}', '#D4852A', 40, 30, 50, 30, 'default', 'Teapp', NULL, TRUE, 'Q11447803'),
  ('Gyeolmyeongja-Cha', 'gyeolmyeongja-cha', '', '결명자차', 'beverage made by infusing roasted sicklepod grains', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q12583504'),
  ('Jin Jun Mei tea', 'jin-jun-mei-tea', '', '金駿眉', 'type of black tea from the Wuyi Mountains in Fujian Province, China', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q15894315'),
  ('Baimao Hou', 'baimao-hou', '', '白毛猴', 'green tea from the Taimu Mountains in Fujian Province, China', '', 'green', '', '', 75, 2, 3, '', '{}', '{}', '#7BA05B', 0, 10, 20, 20, 'default', 'Teapp', NULL, TRUE, 'Q16241448'),
  ('Kangra tea', 'kangra-tea', '', '', 'black or green tea from the Kangra district, India', '', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q22659278'),
  ('Omija-Cha', 'omija-cha', '', '오미자차', 'traditional Korean beverage made by infusing dried magnolia berries', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q28533123'),
  ('Peach Blossom Tea', 'peach-blossom-tea', '', '', 'traditional Korean beverage made by infusing the dried peach flowers', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30043849'),
  ('Gyepi-Cha', 'gyepi-cha', '', '계피차', 'herbal tea', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 0, 20, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30043882'),
  ('Ssuk-Cha', 'ssuk-cha', '', '쑥차', 'traditional Korean beverage made by infusing the dried leaves of mugwort', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30043962'),
  ('Yulmu-Cha', 'yulmu-cha', '', '율무차', 'beverage made with the flour of roasted grains of Job''s tears', 'Korea', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q30043999'),
  ('Lotus Tea', 'lotus-tea', '', '연잎차', 'beverage made by infusing leaves, flowers, roots of lotus', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q50304474'),
  ('Dried Lime Tea', 'dried-lime-tea', '', '', 'A beverage that widely consumed in Iraq , Kuwait , Oman and United Arab Emirates.', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q56276135'),
  ('Root Tea', 'root-tea', '', '', 'traditional Korean beverages made of roots, shoots, and barks of various plants', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q111028903'),
  ('Seed Tea', 'seed-tea', '', '', 'traditional Korean beverages made of seeds of various plants', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q111028971'),
  ('Yesheng Bai Ya tea', 'yesheng-bai-ya-tea', '', '野生白芽', 'Chinese white tea', 'People''s Republic of China', 'white', '', '', 80, 3, 3, '', '{}', '{}', '#C8C4B0', 10, 5, 20, 10, 'default', 'Teapp', NULL, TRUE, 'Q115300807'),
  ('Wakoucha', 'wakoucha', '', '和紅茶', 'black tea that is produced in Japan', 'Japan', 'black', '', '', 95, 4, 2, '', '{}', '{}', '#8B4513', 90, 70, 62, 45, 'default', 'Teapp', NULL, TRUE, 'Q125307881'),
  ('Yuja-Cha', 'yuja-cha', '', '유자차', 'traditional Korean beverage made by diluting yuzu marmalade with water', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q31511'),
  ('Barley Tea', 'barley-tea', '', '麦茶', 'infusion made from roasted barley grains', '', 'tisane', '', '', 100, 5, 2, '', '{}', '{}', '#C0856A', 40, 30, 25, 20, 'default', 'Teapp', NULL, TRUE, 'Q31625');
ON CONFLICT (slug) DO UPDATE SET
  phonetic_name = EXCLUDED.phonetic_name,
  original_name = EXCLUDED.original_name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  brewing_num_brews = EXCLUDED.brewing_num_brews,
  brewing_instructions = EXCLUDED.brewing_instructions,
  health_benefits = EXCLUDED.health_benefits,
  color_hex = EXCLUDED.color_hex,
  oxidation_level = EXCLUDED.oxidation_level,
  roast_level = EXCLUDED.roast_level,
  flavor_x = EXCLUDED.flavor_x,
  flavor_y = EXCLUDED.flavor_y,
  source_type = 'default',
  source = 'Teapp',
  is_public = TRUE;

-- Migrate existing custom_teas into teas table, then drop custom_teas
INSERT INTO teas (name, slug, description, tea_type, origin, caffeine_level, brewing_temp_c, brewing_time_min, characteristics, source_type, source, owner_id, is_public)
SELECT name, slug, description, tea_type, origin, caffeine_level,
  brewing_temp_c::int, brewing_time_min::int, characteristics,
  'user', 'custom', user_id, FALSE
FROM custom_teas
ON CONFLICT (slug) DO NOTHING;

-- Update user_teas: custom tea references now point to teas table
UPDATE user_teas ut
SET tea_id = (SELECT id FROM teas t WHERE t.slug = (SELECT slug FROM custom_teas ct WHERE ct.id = ut.tea_id))
WHERE tea_id NOT IN (SELECT id FROM teas);

-- Update tea_logs: custom tea references now point to teas table
UPDATE tea_logs tl
SET tea_id = (SELECT id FROM teas t WHERE t.slug = (SELECT slug FROM custom_teas ct WHERE ct.id = tl.tea_id))
WHERE tea_id NOT IN (SELECT id FROM teas);

-- Drop custom_teas table
DROP TABLE IF EXISTS custom_teas;

-- Add accent_color to user_preferences
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#c4853f';
