-- Rename teas to original (romanized native) names + fill original_name (Sep 2026)
UPDATE teas SET name = 'Jin Xuan', original_name = '金萱' WHERE slug = 'milky-oolong';
UPDATE teas SET name = 'Qing Xin Oolong', original_name = '青心烏龍' WHERE slug = 'organic-jade-oolong';
UPDATE teas SET name = 'Shui Xian', original_name = '水仙' WHERE slug = 'organic-china-leaf-oolong-shui-xian';
UPDATE teas SET name = 'Da Hong Pao', original_name = '大红袍' WHERE slug = 'dahongpao-zhengyan-yancha';
UPDATE teas SET name = 'Qimen Hongcha', original_name = '祁门红茶' WHERE slug = 'organic-keemun';
UPDATE teas SET name = 'Jin Hou Hongcha', original_name = '金猴红茶' WHERE slug = 'organic-golden-yunnan';
UPDATE teas SET name = 'Jin Hou Hongcha', original_name = '金猴红茶' WHERE slug = 'organic-pan-yong-golden-monkey';
UPDATE teas SET name = 'Yunnan Hong', original_name = '滇红' WHERE slug = 'organic-muscatel-dragon-yunnan';
UPDATE teas SET name = 'Bai Fenghuang', original_name = '白凤凰' WHERE slug = 'organic-white-phoenix';
UPDATE teas SET name = 'Shou Puer', original_name = '熟普洱' WHERE slug = 'organic-pu-erh-ripe-in-loose-weight';
UPDATE teas SET name = 'Lunan Gushu Sheng 2022', original_name = '布朗山古树生茶' WHERE slug = 'lunan-ancient-trees-sheng-puer-2022';
UPDATE teas SET name = 'Lunan Gushu Sheng 2020', original_name = '布朗山古树生茶' WHERE slug = 'lunan-sheng-puer-ancient-trees-2020';
UPDATE teas SET name = 'Nannuo Yesheng Sheng 2012', original_name = '南糯山野生生茶' WHERE slug = 'nannuo-sheng-puer-wild-forest-2012';
UPDATE teas SET name = 'Chama Gudao Shou 2006', original_name = '茶马古道熟茶' WHERE slug = 'tea-horse-road-shu-puer-2006';
UPDATE teas SET name = 'Nannuo Dianhong', original_name = '南糯滇红' WHERE slug = 'wild-forest-nannuo-dianhong';
UPDATE teas SET name = 'Yueguanbai 2026', original_name = '月光白' WHERE slug = 'lunan-ancient-trees-yueguanbai-white-tea-2026';
UPDATE teas SET name = 'Yueguangbai 2026', original_name = '月光白' WHERE slug = 'nannuo-forest-trees-yueguangbai-white-tea-2026';
UPDATE teas SET name = 'Yueguangbai 2025', original_name = '月光白' WHERE slug = 'lunan-yueguangbai-stone-pressed-2025';
UPDATE teas SET name = 'Liu''an Guapian', original_name = '六安瓜片' WHERE slug = 'luan-guapian';
UPDATE teas SET name = 'Hei Moli Zhucha', original_name = '黑茉莉珠茶' WHERE slug = 'organic-black-jasmine-pearls';
UPDATE teas SET name = 'Fukamushi Kabusecha', original_name = '深蒸しかぶせ茶' WHERE slug = 'fukamushi-kabusecha-shade-grown-slow-steamed';
UPDATE teas SET name = 'Saga no Yuki Genmaicha', original_name = '佐賀の雪玄米茶' WHERE slug = 'genmaicha-with-roasted-brown-rice-saga-no-yuki';
UPDATE teas SET name = 'Oku no Tsuyu', original_name = '奥の露' WHERE slug = 'gyokuro-oku-no-tsuyu';
UPDATE teas SET name = 'Yame Gyokuro', original_name = '八女玉露' WHERE slug = 'gyokuro-yame';
UPDATE teas SET name = 'Hojicha-ko', original_name = '焙じ茶粉' WHERE slug = 'koyamaen-hojicha-powder';
UPDATE teas SET name = 'Yuzu Kukicha', original_name = '柚子茎茶' WHERE slug = 'kukicha-with-yuzu';
UPDATE teas SET name = 'Kabuse Okumidori', original_name = 'かぶせ奥緑' WHERE slug = 'kabuse-okumidori-sencha-for-cold-brew';
UPDATE teas SET name = 'Kabusecha', original_name = 'かぶせ茶' WHERE slug = 'kabusecha-shade-grown-2025';
UPDATE teas SET name = 'Hokkyokusei', original_name = '北極星' WHERE slug = 'hokkyokusei-special-blend-sencha-tea';
UPDATE teas SET name = 'Mizudashi Sencha', original_name = '水出し煎茶' WHERE slug = 'mizudashi-sencha-with-matcha-for-cold-brew-iced-tea';
UPDATE teas SET name = 'Mugicha', original_name = '麦茶' WHERE slug = 'mugi-cha-japanese-barley-tea';
UPDATE teas SET name = 'Kuro Gyokuro', original_name = '黒玉露' WHERE slug = 'natural-black-gyokuro';
UPDATE teas SET name = 'Okumidori Matcha', original_name = '奥緑' WHERE slug = 'natural-okumidori-matcha-25g-tin-ceremonial';
UPDATE teas SET name = 'Okumidori Matcha', original_name = '奥緑' WHERE slug = 'okumidori-matcha-25g-tin-ceremonial';
UPDATE teas SET name = 'Samidori Matcha', original_name = '薗北' WHERE slug = 'samidori-matcha-25g-tin-ceremonial';
UPDATE teas SET name = 'Genmai', original_name = '玄米' WHERE slug = 'obubu-genmai-roasted-brown-rice';
UPDATE teas SET name = 'Gyokuro Kiwami', original_name = '玉露極' WHERE slug = 'premium-gyokuro-kiwami';
UPDATE teas SET name = 'Shincha No. 120', original_name = '新茶' WHERE slug = 'premium-shincha-no-120-2026';
UPDATE teas SET name = 'Agata no Mori', original_name = '県の森' WHERE slug = 'sencha-agata-no-mori';
UPDATE teas SET name = 'Dosenbo Ippin', original_name = '洞川仙品' WHERE slug = 'sencha-dosenbo-ippin-sencha';
UPDATE teas SET name = 'Instant Sencha', original_name = 'インスタント煎茶' WHERE slug = 'sencha-instant-40-grams';
UPDATE teas SET name = 'Meikun', original_name = '明君' WHERE slug = 'sencha-meikun';
UPDATE teas SET name = 'Midori', original_name = 'みどり' WHERE slug = 'sencha-midori';
UPDATE teas SET name = 'Midori Nibancha', original_name = 'みどり二番茶' WHERE slug = 'sencha-midori-nibancha';
UPDATE teas SET name = 'Sencha Shuppin', original_name = '煎茶秀品' WHERE slug = 'sencha-shuppin-2024-exhibition-tea';
UPDATE teas SET name = 'Shiro Houji', original_name = '白焙じ' WHERE slug = 'white-leaf-hojicha';
UPDATE teas SET name = 'Benifuki', original_name = 'べにふうき' WHERE slug = 'organic-benifuki';
UPDATE teas SET name = 'Kagoshima Matcha No. 90', original_name = '鹿児島抹茶' WHERE slug = 'organic-kagoshima-matcha-no-90';
UPDATE teas SET name = 'Oyatoko no Hojicha', original_name = 'オヤトコの焙じ茶' WHERE slug = 'oyatoko-no-hojicha';
UPDATE teas SET name = 'Hwangcha', original_name = '황차' WHERE slug = 'hwang-cha';
UPDATE teas SET name = 'Hadong Hwangcha', original_name = '하동황차' WHERE slug = 'hadong-yellow-tea';
UPDATE teas SET name = 'Jeju Gyul-hyang', original_name = '귤향' WHERE slug = 'ido-jeju-tangerine-peel-tea-50-gram';
UPDATE teas SET name = 'Pyogo-cha', original_name = '표고차' WHERE slug = 'shiitake-mushroom-tea';
UPDATE teas SET name = 'Sum-cha', original_name = '숨차' WHERE slug = 'breathing-tea-fermented-herbs';
UPDATE teas SET name = 'Joseuk-cha', original_name = '조숙차' WHERE slug = 'good-night-tea-fermented-herbs';
UPDATE teas SET name = 'Gabyul-cha', original_name = '가별차' WHERE slug = 'light-tea-fermented-herbs';
UPDATE teas SET name = 'Pungwol-cha', original_name = '풍월차' WHERE slug = 'relief-tea-fermented-herbs';
UPDATE teas SET name = 'Sucho-cha', original_name = '수초차' WHERE slug = 'willowy-tea-fermented-herbs';
UPDATE teas SET original_name = '抹茶入り玄米茶' WHERE slug = 'genmaicha-with-matcha';
UPDATE teas SET original_name = '玉露秀品' WHERE slug = 'gyokuro-shuppin';
UPDATE teas SET original_name = '焙じ茶' WHERE slug = 'hojicha-gold';
UPDATE teas SET original_name = '本玉露' WHERE slug = 'hon-gyokuro-mare';
UPDATE teas SET original_name = '抹茶入り煎茶' WHERE slug = 'sencha-with-matcha';
UPDATE teas SET original_name = 'つぐみ' WHERE slug = 'tsugumi';
UPDATE teas SET original_name = '春ほのか' WHERE slug = 'haru-honoka';
UPDATE teas SET original_name = '限定煎茶' WHERE slug = 'sencha-limited';
UPDATE teas SET original_name = '玉露' WHERE slug = 'gyokuro-classic-edible-leaves';UPDATE teas SET name = 'Laoman''e Shou 2022', original_name = '老曼峨熟茶' WHERE slug = 'laomane-shu-pu-erh-2022';
UPDATE teas SET name = 'Kirishima Sencha', original_name = '霧島煎茶' WHERE slug = 'organic-sencha-kirishima';
UPDATE teas SET name = 'Oritaen Sencha', original_name = '折田園煎茶' WHERE slug = 'organic-sencha-oritaen';
UPDATE teas SET name = 'Mumon', original_name = '無門' WHERE slug = 'matcha-mumon';
UPDATE teas SET name = 'Narino', original_name = '成仁' WHERE slug = 'matcha-narino-20g-ceremonial';
UPDATE teas SET name = 'Uji Mukashi', original_name = '宇治昔' WHERE slug = 'matcha-uji-mukashi';
UPDATE teas SET name = 'Meiju', original_name = '明成' WHERE slug = 'matcha-meiju-marukyu-koyamaen-ceremonial';
UPDATE teas SET name = 'Oju', original_name = '皇祝' WHERE slug = 'matcha-oju-marukyu-koyamaen-ceremonial';
UPDATE teas SET name = 'Unkaku', original_name = '雲鶴' WHERE slug = 'matcha-unkaku-marukyu-koyamaen-ceremonial';
UPDATE teas SET name = 'Wako', original_name = '和光' WHERE slug = 'matcha-wako-marukyu-koyamaen-ceremonial';
UPDATE teas SET name = 'Yamabuki', original_name = '山吹' WHERE slug = 'japanese-matcha-yamabuki-top-quality-for-matcha-latte';
UPDATE teas SET name = 'Ajisai', original_name = '紫陽花' WHERE slug = 'matcha-ajisai-obubu-top-quality-for-matcha-latte';
UPDATE teas SET name = 'Himawari', original_name = 'ひまわり' WHERE slug = 'matcha-himawari-hiraoka-top-quality-for-matcha-latte';
UPDATE teas SET original_name = 'कांगड़ा चाय' WHERE slug = 'kangra-tea';
UPDATE teas SET original_name = 'दार्जिलिंग' WHERE slug = 'darjeeling-1st-flush-2026-maharani-hills';