-- Rivers and Lakes Tea: Zhengyan Series rock oolongs (from zhengyan-true-cliff-rock-oolong page)
-- 10 teas, extracted as individual teas from the series page (sold as 7g session packets).
-- Producers: Shengfa (DSK), Asong (HYK), Shiqi "17" (Zhuke/Shijiao etc). All rested 1-2 yrs post roast.
-- Locale/cultivar names verified: Miaolian 妙莲 (Lotus Peak area), Da Keng Kou 大坑口, Hui Yuan Keng 慧苑坑,
-- Guanyin Yan 观音岩, Dao Shui Keng 倒水坑, Zhuke 竹窠 + Aijiao Wulong 矮脚乌龙 (Beiyuan heritage cv),
-- Shijiao 石角, Ma Tou Yan 马头岩, Beidou 北斗 (true DHP cv).
INSERT INTO teas (name, slug, phonetic_name, original_name, description, origin, tea_type, category, caffeine_level, brewing_temp_c, brewing_time_min, brewing_num_brews, brewing_instructions, characteristics, health_benefits, color_hex, oxidation_level, roast_level, flavor_x, flavor_y, source_type, source, owner_id, is_public) VALUES
  ('Miaolian Shui Xian', 'miaolian-shui-xian', 'Miàolián Shuǐxiān', '妙莲水仙', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Zhengyan ("true cliff") Shui Xian rock oolong from the Miaolian grove in the Wuyi Mountain core, roasted medium and rested.', 'Miaolian, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Mineral', 'Floral', 'Roasted', 'Smooth']::text[], ARRAY[]::text[], '#D4852A', 45, 50, 58, 32, 'default', 'Teapp', NULL, TRUE),
  ('Da Keng Kou Lao Cong Shui Xian', 'da-keng-kou-lao-cong-shui-xian', 'Dàkēngkǒu Lǎocōng Shuǐxiān', '大坑口老枞水仙', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Old bush (lao cong) Shui Xian from the Da Keng Kou grove in the Wuyi core — a tea displaying both yanyun "rock charm" and congwei "mossy thicket taste".

This one is featured as the tea displaying qualities of both yanyun and congwei "thicket taste" in the box set Old Thicket 2.0.', 'Da Keng Kou, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Mineral', 'Mossy', 'Woody', 'Roasted']::text[], ARRAY[]::text[], '#D4852A', 45, 50, 55, 30, 'default', 'Teapp', NULL, TRUE),
  ('Hui Yuan Keng 100 Year Shui Xian', 'hui-yuan-keng-100-year-shui-xian', 'Huìyuàn Kēng Bǎinián Lǎocōng Shuǐxiān', '慧苑坑百年老枞水仙', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Centenarian old bush Shui Xian from Hui Yuan Keng, one of the famed "three pits" (三坑) of the Wuyi core, medium roasted.', 'Hui Yuan Keng, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Mineral', 'Mossy', 'Sweet', 'Woody']::text[], ARRAY[]::text[], '#D4852A', 45, 48, 54, 31, 'default', 'Teapp', NULL, TRUE),
  ('Guanyin Yan Rougui', 'guanyin-yan-rougui', 'Guānyīn Yán Ròuguì', '观音岩肉桂', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Cassia-aroma Rougui rock oolong from the Guanyin Yan ("Guanyin Rock") grove in the Wuyi core.', 'Guanyin Yan, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Cinnamon', 'Spicy', 'Mineral', 'Roasted']::text[], ARRAY[]::text[], '#D4852A', 50, 55, 62, 30, 'default', 'Teapp', NULL, TRUE),
  ('Hui Yuan Keng Rougui', 'hui-yuan-keng-rougui', 'Huìyuàn Kēng Ròuguì', '慧苑坑肉桂', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Rougui rock oolong from Asong''s family gardens in Hui Yuan Keng — one of the 13 original families owning (not contracting) roughly 50亩 (over 8 acres) there.', 'Hui Yuan Keng, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Cinnamon', 'Mineral', 'Roasted', 'Bold']::text[], ARRAY[]::text[], '#D4852A', 50, 55, 63, 29, 'default', 'Teapp', NULL, TRUE),
  ('Dao Shui Keng Rougui', 'dao-shui-keng-rougui', 'Dàoshuǐ Kēng Ròuguì', '倒水坑肉桂', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Shengfa''s third-generation DSK Rougui — material from the legendary Dao Shui Keng grove, among the smoothest Rougui the shop has tried.

Coupled with material from legendary Dao Shui Keng, this man''s DSK Rougui is an absolute treat.', 'Dao Shui Keng, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Cinnamon', 'Smooth', 'Mineral', 'Roasted']::text[], ARRAY[]::text[], '#D4852A', 50, 52, 60, 32, 'default', 'Teapp', NULL, TRUE),
  ('Zhuke Aijiao Wulong', 'zhuke-aijiao-wulong', 'Zhúkē Āijiǎo Wūlóng', '竹窠矮脚乌龙', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

True-cliff rock oolong of the heritage Aijiao Wulong ("dwarf-legged wulong") cultivar from the Zhuke grove — Shiqi "17" sells it as "Dwarf-Legged Wulong".

As a producer who likes to age his yancha, this is 17''s favorite varietal to work with due to its ability to maintain its distinctive aroma-flavor characteristics in storage longer than others. A heritage cultivar with a history of over 100 years representing some of the earliest genetic lines of breeding in the Beiyuan tribute tea area, this cultivar likely was named after its smaller leaf, densely branched, lower to the ground, scrubbier growth pattern.', 'Zhuke, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Mineral', 'Floral', 'Roasted', 'Distinctive']::text[], ARRAY[]::text[], '#D4852A', 48, 55, 60, 30, 'default', 'Teapp', NULL, TRUE),
  ('Shijiao Lao Cong Mei Zhan', 'shijiao-lao-cong-mei-zhan', 'Shíjiǎo Lǎocōng Méizhàn', '石角老丛梅占', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Old bush Mei Zhan cultivar rock oolong from the Shijiao grove in the Wuyi core.', 'Shijiao, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Plum', 'Floral', 'Mineral', 'Roasted']::text[], ARRAY[]::text[], '#D4852A', 50, 52, 61, 31, 'default', 'Teapp', NULL, TRUE),
  ('Ma Tou Yan Tie Luo Han', 'ma-tou-yan-tie-luo-han', 'Mǎtóuyán Tiě Luóhàn', '马头岩铁罗汉', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

Heirloom Tie Luo Han ("Iron Arhat") — one of the earliest Wuyi famous cultivars — from the Ma Tou Yan grove, given a high roast.

The heaviest roasted tea featured in our flagship Wuyi box, THEA BOHEA.', 'Ma Tou Yan, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Roasted', 'Mineral', 'Bold', 'Woody']::text[], ARRAY[]::text[], '#D4852A', 50, 75, 70, 27, 'default', 'Teapp', NULL, TRUE),
  ('Hui Yuan Keng Beidou Da Hong Pao', 'hui-yuan-keng-beidou-da-hong-pao', 'Huìyuàn Kēng Běidǒu Dàhóngpáo', '慧苑坑北斗大红袍', 'The core tea production arena in the Wuyi Mountains referred to as 正岩 zheng yan "true cliff" is regarded as the highest pedigree of terroir when it comes to Rock Oolong: jagged, idyllic cliffs harbor tea gardens between them, feeding the soil a consistent runoff of minerals experienced in the finished tea as 岩韵 yan yun "rock charm". All ten teas rested 1–2 years after their last roasting, allowing the necessary 退火 "retreating fire".

Over the last seven years of traveling to, developing relationships in, and continually learning about and tasting rock oolong, Rivers and Lakes curated a lineup of high quality, genuine, true cliff Wuyi teas — sold here as 7g session packets. Producers: Shengfa, a third generation tea maker whose Dao Shui Keng Rougui is among the smoothest; Asong, married into one of the 13 original Hui Yuan Keng families who own (and don''t contract out) around 50亩 (over 8 acres) there; and Shiqi "17", a well-connected tea project leader contracting fresh leaves from sought micro terroirs around Shui Lian Dong and Hui Yuan Keng — many of his teas are lao cong, heavier roasted, often semi-wild seed grown, from unpruned gardens.

High-fire Da Hong Pao of the true Beidou ("Big Dipper") DHP cultivar from Hui Yuan Keng — the darkest, richest, most layered of the series, with a bit of ripened age.

The darkest, most roastiest yancha (with a nice ripened bit of age on it as well), this high fire Da Hong Pao is arguably the most rich and layered of the bunch. Pure Mrs. Trunchbull''s cake. Also featured in the FIRE SET box.', 'Hui Yuan Keng, Wuyishan, Nanping, Fujian, China', 'oolong', 'true_tea', 'medium', 95, 1, 6, 'Use 5g per 150ml at 95–100°C. Quick rinse; steep 20–40 seconds; re-steep 5–7 times.', ARRAY['Roasted', 'Rich', 'Layered', 'Mineral']::text[], ARRAY[]::text[], '#D4852A', 55, 75, 72, 28, 'default', 'Teapp', NULL, TRUE);
